spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/olive?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC
    username: root
    password: 461352
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database: mysql

